In [3]:
import numpy as np
x = np.array([1,3,5])
print(x.mean())
print(x.shape)
a = np.array([[1,2,3], [2,3,4]])
print(a.shape)


3.0
(3,)
(2, 3)


In [5]:
x = np.array([1,3,5,7,9,11]).reshape(3,2)
print(x)
y = np.ones([3, 4])
print(y)

[[ 1  3]
 [ 5  7]
 [ 9 11]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [9]:
list1 = [[1,11],[2,12],[3,13]]
np_ary = np.array(list1)
print(np_ary[:, 1])


[11 12 13]


In [10]:
np.sqrt([2, 3, 4])

array([1.41421356, 1.73205081, 2.        ])

In [3]:
import numpy as np
a = np.arange(15)
print(a)
a = np.arange(15).reshape(3, 5)
print(a)
print(a[1,1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
6


In [4]:
import numpy as np
zero_vector = np.zeros(3)
print(zero_vector)

[0. 0. 0.]


In [5]:
import numpy as np
my_arr = np.zeros(15).reshape(3,5)
my_arr += 4
my_arr

array([[4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4.]])

In [6]:
import numpy as np
arr = np.array([[1,2],[3,4]])
print(arr.transpose())

[[1 3]
 [2 4]]


In [8]:
x = [1, 2, 3]
y = [4, 5, 6]
z = x + y
print(z)

import numpy as np

x = np.array([1,2,3])
y = np.array([4,5,6])
z = x + y
print(z)

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [11]:
import numpy as np
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[:,1]+y[:,1])

[ 4 10 16]


In [12]:
import numpy as np
a = np.array([10,20,30,40,50,60,70])
i = [1,3,5]
print(a[i])

[20 40 60]


In [ ]:
import numpy as np
a = np.array([10,20,30,40,50,60,70])
b = a[1:6:2] #
print('b:', b)
b[1] = 10 
print('b:', b)
print('a:', a) # a 값도 수정됨 따라서 b = np.array(a[1:6:2])로 수정해야함

b: [20 40 60]
b: [20 10 60]
a: [10 20 30 10 50 60 70]


In [14]:
import numpy as np
a = np.array([10,20,30,40,50,60,70])
b = a > 50
print(b)

[False False False False False  True  True]


In [ ]:
import numpy as np
arr = np.random.random(5) # 0~1사이 무작위수 5개 
print(arr)
print(np.all(arr >= 0.3))
print(np.any(arr > 0.7))

[0.17998822 0.34862948 0.2819307  0.80555963 0.46331323]
False
True


In [18]:
import numpy as np
height = np.array([173, 168, 171, 189, 179])
weight = np.array([65.4, 59.2, 63.6, 88.4, 68.7])
bmi = weight/(height**2)*10000
print(bmi)
a = bmi > 21
print(a)

[21.85171573 20.97505669 21.75028214 24.7473475  21.44127836]
[ True False  True  True  True]


In [20]:
np.linspace(0,12,4)
np.linspace(0,12,4, retstep=True)

(array([ 0.,  4.,  8., 12.]), np.float64(4.0))

In [ ]:
np.linspace(0,12,4, endpoint=False) # 우선 5개의 등간격으로 나누고 마지막 원소를 지워서 표현

array([0., 3., 6., 9.])

In [22]:
np.logspace(np.log10(10), np.log10(100), 5)

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])